development:
  host: localhost
  database: sanderstead_parish_development

test:
  host: localhost
  database: sanderstead_parish_test

# set these environment variables on your prod server
production:
  host: localhost
  database: sanderstead_parish_production
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
